<?php

require_once 'PHPUnit/Framework.php';

class TestWhat extends MakeItWhat {

	var $colour;
	var $size;
	var $shape;
}

/**
 * Test class for MakeItWhat.
 * Generated by PHPUnit on 2010-08-09 at 15:36:09.
 */
class MakeItWhatTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var MakeItWhat
	 */
	protected $what;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		//$this->what = new TestWhat();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testLoad().
	 */
	public function testLoad() {
		$this->what->load('whatExample1.xml');
		$this->assertType('SimpleXMLElement',$this->what->xml);
		$this->assertEquals('/var/www/mysite',$this->what->getXpathValue('website/path'));
		$this->assertEquals('red',$this->what->colour);
		$this->assertEquals('medium',$this->what->size);
		$this->assertEquals(null,$this->what->shape);
		$this->assertEquals(null,$this->what->getXpathValue('somepath'));
		$this->assertEquals(null,$this->what->getXpathValue('some/wrong/path'));
	}

}
?>
